// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAv714tDiValsGP3ZO80K4F4syv_XKNBw',
    appId: '1:459342442820:web:c8c57c1d9338015eeda711',
    messagingSenderId: '459342442820',
    projectId: 'dodiddone-64f1a',
    authDomain: 'dodiddone-64f1a.firebaseapp.com',
    storageBucket: 'dodiddone-64f1a.appspot.com',
    measurementId: 'G-WW90FMEYN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6nrMDS-24i0RJAi1xytwxMZnQGpR22Ug',
    appId: '1:459342442820:android:bcfb0ac3d9c93c71eda711',
    messagingSenderId: '459342442820',
    projectId: 'dodiddone-64f1a',
    storageBucket: 'dodiddone-64f1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHK85ePPV1QAshRW_4vr5WTXYKTdV5bk',
    appId: '1:459342442820:ios:06958ddeb2ba7996eda711',
    messagingSenderId: '459342442820',
    projectId: 'dodiddone-64f1a',
    storageBucket: 'dodiddone-64f1a.appspot.com',
    iosBundleId: 'com.example.zerocoderdodiddone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAHK85ePPV1QAshRW_4vr5WTXYKTdV5bk',
    appId: '1:459342442820:ios:06958ddeb2ba7996eda711',
    messagingSenderId: '459342442820',
    projectId: 'dodiddone-64f1a',
    storageBucket: 'dodiddone-64f1a.appspot.com',
    iosBundleId: 'com.example.zerocoderdodiddone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAv714tDiValsGP3ZO80K4F4syv_XKNBw',
    appId: '1:459342442820:web:ad1bb0c0fd02deceeda711',
    messagingSenderId: '459342442820',
    projectId: 'dodiddone-64f1a',
    authDomain: 'dodiddone-64f1a.firebaseapp.com',
    storageBucket: 'dodiddone-64f1a.appspot.com',
    measurementId: 'G-R0HRF50SEC',
  );
}
